# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from final5 import Ui_window5
class Ui_window3(object):
    def setupUi(self, window3):
        window3.setObjectName("window3")
        window3.resize(1022, 584)
        self.centralwidget = QtWidgets.QWidget(window3)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(580, 150, 371, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 60, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(60, 150, 371, 241))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 460, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.readdata)
        window3.setCentralWidget(self.centralwidget)

        self.retranslateUi(window3)
        QtCore.QMetaObject.connectSlotsByName(window3)

    #read data from table and store it in a list
    def readdata(self):
        self.data = []
        self.data1 = []
        for i in range(self.tableWidget.rowCount()):
            self.data.append([])
            for j in range(self.tableWidget.columnCount()):
                self.data[i].append(int(self.tableWidget.item(i,j).text()))
        for i in range(self.tableWidget_2.rowCount()):
            self.data1.append([])
            for j in range(self.tableWidget_2.columnCount()):
                self.data1[i].append(int(self.tableWidget_2.item(i,j).text()))
        self.sum = []
        self.available=[]
        for j in range(len(self.data[0])):
            self.sum.append(0)
            for i in range(len(self.data)):
                self.sum[j] += self.data[i][j]
        print(self.sum)
        #calculate maxres - sum
        for i in range(len(self.maxres)):
            self.available.append(self.maxres[i]-self.sum[i])
        print(self.available)
        # self.x=[]
        self.x=self.need()
        self.window5 = QtWidgets.QMainWindow()
        self.ui = Ui_window5()
        self.ui.setupUi(self.window5)
        self.window5.show()
        self.centralwidget.window().hide()
        #send data to window5
        self.ui.getdata(self.data)
        self.ui.getdata1(self.data1)
        self.ui.getavailable(self.available)
        self.ui.getneed(self.x)
        print(self.data)
        print(self.data1)
        self.countx=len(self.x)

        self.countavailable=len(self.available)

        #setting vaues in widgettable in final5
        self.ui.tableWidget.setRowCount(self.countx)
        self.ui.tableWidget.setColumnCount(self.countavailable)
        for i in range(self.countx):
            for j in range(self.countavailable):
                self.ui.tableWidget.setItem(i,j,QtWidgets.QTableWidgetItem(str(self.x[i][j])))
                self.ui.tableWidget.setHorizontalHeaderLabels([f"R{i+1}" for i in range(self.countx)])
                self.ui.tableWidget.setVerticalHeaderLabels([f"P{i+1}" for i in range(int(self.countavailable))])
        self.ui.tableWidget_2.setRowCount(1)
        self.ui.tableWidget_2.setColumnCount(self.countavailable)
        for i in range(self.countavailable):
            self.ui.tableWidget_2.setItem(0,i,QtWidgets.QTableWidgetItem(str(self.available[i])))
            self.ui.tableWidget_2.setHorizontalHeaderLabels([f"R{i+1}" for i in range(int(self.countavailable))])
            self.ui.tableWidget_2.setVerticalHeaderLabels(["Resources"])
        
    #function to calculate need
    def need(self):
        self.need = []
        for i in range(len(self.data)):
            self.need.append([])
            for j in range(len(self.data[0])):
                self.need[i].append(self.data1[i][j]-self.data[i][j])
        #print("hello",self.need)
        return self.need



    #function to get me list from window2
    def getdata(self,maxres):
        self.maxres = maxres
        self.getdata=self.maxres

    def retranslateUi(self, window3):
        _translate = QtCore.QCoreApplication.translate
        window3.setWindowTitle(_translate("window3", "MainWindow"))
        self.label.setText(_translate("window3", "Allocated resources for each process"))
        self.label_2.setText(_translate("window3", "maximum resources for each process"))
        self.pushButton_2.setText(_translate("window3", "calculate"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window3 = QtWidgets.QMainWindow()
    ui = Ui_window3()
    ui.setupUi(window3)
    window3.show()
    sys.exit(app.exec_())
