# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window55.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window55(object):
    def setupUi(self, window55):
        window55.setObjectName("window55")
        window55.resize(686, 530)
        self.centralwidget = QtWidgets.QWidget(window55)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 180, 121, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.outputTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.outputTextEdit.setGeometry(QtCore.QRect(200, 130, 391, 261))
        self.outputTextEdit.setReadOnly(True)
        self.outputTextEdit.setObjectName("outputTextEdit")
        window55.setCentralWidget(self.centralwidget)

        self.retranslateUi(window55)
        QtCore.QMetaObject.connectSlotsByName(window55)

    def retranslateUi(self, window55):
        _translate = QtCore.QCoreApplication.translate
        window55.setWindowTitle(_translate("window55", "MainWindow"))
        self.label.setText(_translate("window55", "output"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window55 = QtWidgets.QMainWindow()
    ui = Ui_window55()
    ui.setupUi(window55)
    window55.show()
    sys.exit(app.exec_())
