# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from final2 import Ui_window2

class Ui_window1(object):
    def setupUi(self, window1):
        window1.setObjectName("window1")
        window1.resize(453, 420)
   
        self.widget = QtWidgets.QWidget(window1)
        self.widget.setObjectName("widget")

        self.firstpage = QtWidgets.QPushButton(self.widget)
        self.firstpage.setGeometry(QtCore.QRect(160, 340, 121, 51))
        self.firstpage.clicked.connect(self.func0)
        self.firstpage.setAutoFillBackground(False)
        self.firstpage.setObjectName("firstpage")


        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 160, 181, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 220, 181, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 160, 121, 20))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 121, 20))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        window1.setCentralWidget(self.widget)

        self.retranslateUi(window1)
        QtCore.QMetaObject.connectSlotsByName(window1)

    def retranslateUi(self, window1):
        _translate = QtCore.QCoreApplication.translate
        window1.setWindowTitle(_translate("window1", "MainWindow"))
        self.firstpage.setText(_translate("window1", "next"))
        self.label.setText(_translate("window1", "Number of processes"))
        self.label_2.setText(_translate("window1", "Number of resources"))
            
    def func0(self):
        self.processes= self.lineEdit.text()
        self.resources= self.lineEdit_2.text()
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_window2()
        self.ui.setupUi(self.window2)
        self.window2.show()
        window1.hide()
        #assign value of int(resources) to number of columns in window2
        
        self.ui.tableWidget.setColumnCount(int(self.resources))
        self.ui.tableWidget.setHorizontalHeaderLabels([f"R{i+1}" for i in range(int(self.resources))])
        self.ui.tableWidget.setVerticalHeaderLabels(["Resources"])
        #send self.processes to window2
        self.ui.getdata(self.processes)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window1 = QtWidgets.QMainWindow()
    ui = Ui_window1()
    ui.setupUi(window1)
    window1.show()
    sys.exit(app.exec_())
